security:
    # Define password hashers
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Define the user provider
    providers:
        db_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: db_provider
            # Configure form login for authentication
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_home
            logout:
                path: app_logout
                target: app_home
            

    access_control:
        # # Allow anonymous access to login and register pages
        # # - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/register$, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        # # Deny access to login and register pages for authenticated users
        # - { path: ^/login$, roles: IS_AUTHENTICATED_FULLY }
        # - { path: ^/register$, roles: IS_AUTHENTICATED_FULLY }
        
